<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Billline extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Billline_model');
    } 

    /*
     * Listing of billline
     */
    function index()
    {
        $data['billline'] = $this->Billline_model->get_all_billline();
        
        $data['_view'] = 'billline/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new billline
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'billid' => $this->input->post('billid'),
				'item' => $this->input->post('item'),
				'description' => $this->input->post('description'),
				'qty' => $this->input->post('qty'),
				'value' => $this->input->post('value'),
				'taxthis' => $this->input->post('taxthis'),
            );
            
            $billline_id = $this->Billline_model->add_billline($params);
            redirect('billline/index');
        }
        else
        {            
            $data['_view'] = 'billline/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a billline
     */
    function edit($id)
    {   
        // check if the billline exists before trying to edit it
        $data['billline'] = $this->Billline_model->get_billline($id);
        
        if(isset($data['billline']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'billid' => $this->input->post('billid'),
					'item' => $this->input->post('item'),
					'description' => $this->input->post('description'),
					'qty' => $this->input->post('qty'),
					'value' => $this->input->post('value'),
					'taxthis' => $this->input->post('taxthis'),
                );

                $this->Billline_model->update_billline($id,$params);            
                redirect('billline/index');
            }
            else
            {
                $data['_view'] = 'billline/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The billline you are trying to edit does not exist.');
    } 

    /*
     * Deleting billline
     */
    function remove($id)
    {
        $billline = $this->Billline_model->get_billline($id);

        // check if the billline exists before trying to delete it
        if(isset($billline['id']))
        {
            $this->Billline_model->delete_billline($id);
            redirect('billline/index');
        }
        else
            show_error('The billline you are trying to delete does not exist.');
    }
    
}
