<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Branch extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Branch_model');
    } 

    /*
     * Listing of branch
     */
    function index()
    {
        $data['branch'] = $this->Branch_model->get_all_branch();
        
        $data['_view'] = 'branch/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new branch
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'companyid' => $this->input->post('companyid'),
				'nameenglish' => $this->input->post('nameenglish'),
				'namearabic' => $this->input->post('namearabic'),
				'address1english' => $this->input->post('address1english'),
				'address1arabic' => $this->input->post('address1arabic'),
				'address2english' => $this->input->post('address2english'),
				'address2arabic' => $this->input->post('address2arabic'),
				'cityenglish' => $this->input->post('cityenglish'),
				'cityarabic' => $this->input->post('cityarabic'),
				'stateenglish' => $this->input->post('stateenglish'),
				'statearabic' => $this->input->post('statearabic'),
				'phone1' => $this->input->post('phone1'),
				'phone2' => $this->input->post('phone2'),
				'fax' => $this->input->post('fax'),
            );
            
            $branch_id = $this->Branch_model->add_branch($params);
            redirect('branch/index');
        }
        else
        {            
            $data['_view'] = 'branch/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a branch
     */
    function edit($id)
    {   
        // check if the branch exists before trying to edit it
        $data['branch'] = $this->Branch_model->get_branch($id);
        
        if(isset($data['branch']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'companyid' => $this->input->post('companyid'),
					'nameenglish' => $this->input->post('nameenglish'),
					'namearabic' => $this->input->post('namearabic'),
					'address1english' => $this->input->post('address1english'),
					'address1arabic' => $this->input->post('address1arabic'),
					'address2english' => $this->input->post('address2english'),
					'address2arabic' => $this->input->post('address2arabic'),
					'cityenglish' => $this->input->post('cityenglish'),
					'cityarabic' => $this->input->post('cityarabic'),
					'stateenglish' => $this->input->post('stateenglish'),
					'statearabic' => $this->input->post('statearabic'),
					'phone1' => $this->input->post('phone1'),
					'phone2' => $this->input->post('phone2'),
					'fax' => $this->input->post('fax'),
                );

                $this->Branch_model->update_branch($id,$params);            
                redirect('branch/index');
            }
            else
            {
                $data['_view'] = 'branch/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The branch you are trying to edit does not exist.');
    } 

    /*
     * Deleting branch
     */
    function remove($id)
    {
        $branch = $this->Branch_model->get_branch($id);

        // check if the branch exists before trying to delete it
        if(isset($branch['id']))
        {
            $this->Branch_model->delete_branch($id);
            redirect('branch/index');
        }
        else
            show_error('The branch you are trying to delete does not exist.');
    }
    
}
