<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Company extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Company_model');
    } 

    /*
     * Listing of company
     */
    function index()
    {
        $data['company'] = $this->Company_model->get_all_company();
        
        $data['_view'] = 'company/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new company
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nameenglish' => $this->input->post('nameenglish'),
				'namearabic' => $this->input->post('namearabic'),
				'address1english' => $this->input->post('address1english'),
				'address1arabic' => $this->input->post('address1arabic'),
				'address2english' => $this->input->post('address2english'),
				'address2arabic' => $this->input->post('address2arabic'),
				'cityenglish' => $this->input->post('cityenglish'),
				'cityarabic' => $this->input->post('cityarabic'),
				'stateenglish' => $this->input->post('stateenglish'),
				'statearabic' => $this->input->post('statearabic'),
				'phone1' => $this->input->post('phone1'),
				'phone2' => $this->input->post('phone2'),
				'fax' => $this->input->post('fax'),
				'enabletaxation' => $this->input->post('enabletaxation'),
				'percentage' => $this->input->post('percentage'),
				'imagepath' => $this->input->post('imagepath'),
            );
            
            $company_id = $this->Company_model->add_company($params);
            redirect('company/index');
        }
        else
        {            
            $data['_view'] = 'company/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a company
     */
    function edit($id)
    {   
        // check if the company exists before trying to edit it
        $data['company'] = $this->Company_model->get_company($id);
        
        if(isset($data['company']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nameenglish' => $this->input->post('nameenglish'),
					'namearabic' => $this->input->post('namearabic'),
					'address1english' => $this->input->post('address1english'),
					'address1arabic' => $this->input->post('address1arabic'),
					'address2english' => $this->input->post('address2english'),
					'address2arabic' => $this->input->post('address2arabic'),
					'cityenglish' => $this->input->post('cityenglish'),
					'cityarabic' => $this->input->post('cityarabic'),
					'stateenglish' => $this->input->post('stateenglish'),
					'statearabic' => $this->input->post('statearabic'),
					'phone1' => $this->input->post('phone1'),
					'phone2' => $this->input->post('phone2'),
					'fax' => $this->input->post('fax'),
					'enabletaxation' => $this->input->post('enabletaxation'),
					'percentage' => $this->input->post('percentage'),
					'imagepath' => $this->input->post('imagepath'),
                );

                $this->Company_model->update_company($id,$params);            
                redirect('company/index');
            }
            else
            {
                $data['_view'] = 'company/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The company you are trying to edit does not exist.');
    } 

    /*
     * Deleting company
     */
    function remove($id)
    {
        $company = $this->Company_model->get_company($id);

        // check if the company exists before trying to delete it
        if(isset($company['id']))
        {
            $this->Company_model->delete_company($id);
            redirect('company/index');
        }
        else
            show_error('The company you are trying to delete does not exist.');
    }
    
}
