<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Customer extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Customer_model');
    } 

    /*
     * Listing of customer
     */
    function index()
    {
        $data['customer'] = $this->Customer_model->get_all_customer();
        
        $data['_view'] = 'customer/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new customer
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'phone' => $this->input->post('phone'),
            );
            
            $customer_id = $this->Customer_model->add_customer($params);
            redirect('customer/index');
        }
        else
        {            
            $data['_view'] = 'customer/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a customer
     */
    function edit($id)
    {   
        // check if the customer exists before trying to edit it
        $data['customer'] = $this->Customer_model->get_customer($id);
        
        if(isset($data['customer']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'phone' => $this->input->post('phone'),
                );

                $this->Customer_model->update_customer($id,$params);            
                redirect('customer/index');
            }
            else
            {
                $data['_view'] = 'customer/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The customer you are trying to edit does not exist.');
    } 

    /*
     * Deleting customer
     */
    function remove($id)
    {
        $customer = $this->Customer_model->get_customer($id);

        // check if the customer exists before trying to delete it
        if(isset($customer['id']))
        {
            $this->Customer_model->delete_customer($id);
            redirect('customer/index');
        }
        else
            show_error('The customer you are trying to delete does not exist.');
    }
    
    function get_customers_by_name_or_phone() {
        header('Content-Type: application/json');
        if (isset($_GET) && count($_GET) > 0) {
            $customerNameOrPhone = $this->input->get('q');
            $customers = $this->Customer_model->get_customer_by_name_or_phone($customerNameOrPhone);
            echo json_encode($customers);
        } else {
            echo "[]";
        }
    }
    
    /*
     * Adding a new customer
     */
    function addAjax()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
                'name' => $this->input->post('name'),
                'phone' => $this->input->post('phone'),
            );
            
            $customer_id = $this->Customer_model->add_customer($params);
            echo json_encode(['success' => true]);
        }
    }  
}
