<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Insurance extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Insurance_model');
    } 

    /*
     * Listing of insurance
     */
    function index()
    {
        $data['insurance'] = $this->Insurance_model->get_all_insurance();
        
        $data['_view'] = 'insurance/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new insurance
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'description' => $this->input->post('description'),
            );
            
            $insurance_id = $this->Insurance_model->add_insurance($params);
            redirect('insurance/index');
        }
        else
        {            
            $data['_view'] = 'insurance/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a insurance
     */
    function edit($id)
    {   
        // check if the insurance exists before trying to edit it
        $data['insurance'] = $this->Insurance_model->get_insurance($id);
        
        if(isset($data['insurance']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'description' => $this->input->post('description'),
                );

                $this->Insurance_model->update_insurance($id,$params);            
                redirect('insurance/index');
            }
            else
            {
                $data['_view'] = 'insurance/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The insurance you are trying to edit does not exist.');
    } 

    /*
     * Deleting insurance
     */
    function remove($id)
    {
        $insurance = $this->Insurance_model->get_insurance($id);

        // check if the insurance exists before trying to delete it
        if(isset($insurance['id']))
        {
            $this->Insurance_model->delete_insurance($id);
            redirect('insurance/index');
        }
        else
            show_error('The insurance you are trying to delete does not exist.');
    }
    
}
