<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jobcard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Jobcard_model');
        $this->load->model('Vehicle_model');
        $this->load->model('Insurance_model');
        $this->load->model('Jcline_model');
        $this->load->model('Customer_model');
    } 

    /*
     * Listing of jobcard
     */
    function index()
    {
        $data['jobcard'] = $this->Jobcard_model->get_all_jobcard();
        
        $data['_view'] = 'jobcard/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new jobcard
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'jobtype' => $this->input->post('jobtype'),
				'insuranceid' => $this->input->post('insuranceid'),
//				'cancled' => $this->input->post('cancled'),
//				'userid' => $this->input->post('userid'),
//				'createddate' => $this->input->post('createddate'),
				'delivereddate' => $this->input->post('delivereddate'),
				'customerfeedback' => $this->input->post('customerfeedback'),
				'customerid' => $this->input->post('customerid'),
				'jobstatus' => $this->input->post('jobstatus'),
				'vehicleid' => $this->input->post('vehicleid'),
            );
            
            $jobcard_id = $this->Jobcard_model->add_jobcard($params);
            redirect('jobcard/edit/'.$jobcard_id);
        }
        else
        {       
            $this->load->helper('url');
            $data["vehicleOptions"] = $this->Vehicle_model->get_all_vehicle();
            $data["insuranceOptions"] = $this->Insurance_model->get_all_insurance();
            $data["custAutocompleteUrl"] = site_url('/customer/get_customers_by_name_or_phone');
            $data['_view'] = 'jobcard/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a jobcard
     */
    function edit($id)
    {   
        // check if the jobcard exists before trying to edit it
        $data['jobcard'] = $this->Jobcard_model->get_jobcard($id);
        $data['customer'] = $this->Customer_model->get_customer($data['jobcard']['customerid']);
        $data['vehicle'] = $this->Vehicle_model->get_vehicle($data['jobcard']['vehicleid']);
        
        if(isset($data['jobcard']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'jobtype' => $this->input->post('jobtype'),
					'insuranceid' => $this->input->post('insuranceid'),
					'cancled' => $this->input->post('cancled'),
					'userid' => $this->input->post('userid'),
					'createddate' => $this->input->post('createddate'),
					'delivereddate' => $this->input->post('delivereddate'),
					'customerfeedback' => $this->input->post('customerfeedback'),
					'customerid' => $this->input->post('customerid'),
					'jobstatus' => $this->input->post('jobstatus'),
					'vehicleid' => $this->input->post('vehicleid'),
                );

                $this->Jobcard_model->update_jobcard($id,$params);            
                redirect('jobcard/index');
            }
            else
            {
                $data["jobLineItems"] = $this->Jcline_model->get_joblines_by_job_card($data['jobcard']['id']);
                $data["custAutocompleteUrl"] = site_url('/customer/get_customers_by_name_or_phone');
                $data['_view'] = 'jobcard/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The jobcard you are trying to edit does not exist.');
    } 

    /*
     * Deleting jobcard
     */
    function remove($id)
    {
        $jobcard = $this->Jobcard_model->get_jobcard($id);

        // check if the jobcard exists before trying to delete it
        if(isset($jobcard['id']))
        {
            $this->Jobcard_model->delete_jobcard($id);
            redirect('jobcard/index');
        }
        else
            show_error('The jobcard you are trying to delete does not exist.');
    }
    
}
