<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Vehicle extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Vehicle_model');
    } 

    /*
     * Listing of vehicle
     */
    function index()
    {
        $data['vehicle'] = $this->Vehicle_model->get_all_vehicle();
        
        $data['_view'] = 'vehicle/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new vehicle
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'customerid' => $this->input->post('customerid'),
				'make' => $this->input->post('make'),
				'model' => $this->input->post('model'),
				'number' => $this->input->post('number'),
            );
            
            $vehicle_id = $this->Vehicle_model->add_vehicle($params);
            redirect('vehicle/index');
        }
        else
        {            
            $data['_view'] = 'vehicle/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a vehicle
     */
    function edit($id)
    {   
        // check if the vehicle exists before trying to edit it
        $data['vehicle'] = $this->Vehicle_model->get_vehicle($id);
        
        if(isset($data['vehicle']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'customerid' => $this->input->post('customerid'),
					'make' => $this->input->post('make'),
					'model' => $this->input->post('model'),
					'number' => $this->input->post('number'),
                );

                $this->Vehicle_model->update_vehicle($id,$params);            
                redirect('vehicle/index');
            }
            else
            {
                $data['_view'] = 'vehicle/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The vehicle you are trying to edit does not exist.');
    } 

    /*
     * Deleting vehicle
     */
    function remove($id)
    {
        $vehicle = $this->Vehicle_model->get_vehicle($id);

        // check if the vehicle exists before trying to delete it
        if(isset($vehicle['id']))
        {
            $this->Vehicle_model->delete_vehicle($id);
            redirect('vehicle/index');
        }
        else
            show_error('The vehicle you are trying to delete does not exist.');
    }
    
}
