<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Billline_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get billline by id
     */
    function get_billline($id)
    {
        return $this->db->get_where('billline',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all billline
     */
    function get_all_billline()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('billline')->result_array();
    }
        
    /*
     * function to add new billline
     */
    function add_billline($params)
    {
        $this->db->insert('billline',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update billline
     */
    function update_billline($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('billline',$params);
    }
    
    /*
     * function to delete billline
     */
    function delete_billline($id)
    {
        return $this->db->delete('billline',array('id'=>$id));
    }
}
