<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Branch_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get branch by id
     */
    function get_branch($id)
    {
        return $this->db->get_where('branch',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all branch
     */
    function get_all_branch()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('branch')->result_array();
    }
        
    /*
     * function to add new branch
     */
    function add_branch($params)
    {
        $this->db->insert('branch',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update branch
     */
    function update_branch($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('branch',$params);
    }
    
    /*
     * function to delete branch
     */
    function delete_branch($id)
    {
        return $this->db->delete('branch',array('id'=>$id));
    }
}
