<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Customer_model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    /*
     * Get customer by id
     */

    function get_customer($id) {
        return $this->db->get_where('customer', array('id' => $id))->row_array();
    }

    /*
     * Get all customer
     */

    function get_all_customer() {
        $this->db->order_by('id', 'desc');
        return $this->db->get('customer')->result_array();
    }

    /*
     * function to add new customer
     */

    function add_customer($params) {
        $this->db->insert('customer', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update customer
     */

    function update_customer($id, $params) {
        $this->db->where('id', $id);
        return $this->db->update('customer', $params);
    }

    /*
     * function to delete customer
     */

    function delete_customer($id) {
        return $this->db->delete('customer', array('id' => $id));
    }

    /*
     * Get customer by name
     */

    function get_customer_by_name($name) {
        return $this->db->get_where('customer', array('name' => $name))->result_array();
    }

    /*
     * Get customer by phone
     */

    function get_customer_by_phone($phone) {
        return $this->db->get_where('customer', array('phone' => $phone))->result_array();
    }

    /*
     * Get customer by name or phone
     */

    function get_customer_by_name_or_phone($nameOrPhone) {
        if ($nameOrPhone) {
            $query = $this->db->select(['id as value', 'name as text'])->from('customer')->like('name', $nameOrPhone)->or_like('phone', $nameOrPhone);
        } else {
            return [];
        }

        return $query->get()->result_array();
    }

}
