<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jobcard_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get jobcard by id
     */
    function get_jobcard($id)
    {
        return $this->db->get_where('jobcard',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all jobcard
     */
    function get_all_jobcard()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('jobcard')->result_array();
    }
        
    /*
     * function to add new jobcard
     */
    function add_jobcard($params)
    {
        $this->db->insert('jobcard',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update jobcard
     */
    function update_jobcard($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('jobcard',$params);
    }
    
    /*
     * function to delete jobcard
     */
    function delete_jobcard($id)
    {
        return $this->db->delete('jobcard',array('id'=>$id));
    }
}
