<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Qline_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get qline by id
     */
    function get_qline($id)
    {
        return $this->db->get_where('qline',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all qline
     */
    function get_all_qline()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('qline')->result_array();
    }
        
    /*
     * function to add new qline
     */
    function add_qline($params)
    {
        $this->db->insert('qline',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update qline
     */
    function update_qline($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('qline',$params);
    }
    
    /*
     * function to delete qline
     */
    function delete_qline($id)
    {
        return $this->db->delete('qline',array('id'=>$id));
    }
}
