<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Quotation_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get quotation by id
     */
    function get_quotation($id)
    {
        return $this->db->get_where('quotation',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all quotation
     */
    function get_all_quotation()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('quotation')->result_array();
    }
        
    /*
     * function to add new quotation
     */
    function add_quotation($params)
    {
        $this->db->insert('quotation',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update quotation
     */
    function update_quotation($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('quotation',$params);
    }
    
    /*
     * function to delete quotation
     */
    function delete_quotation($id)
    {
        return $this->db->delete('quotation',array('id'=>$id));
    }
}
