<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Vehicle_model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    /*
     * Get vehicle by id
     */

    function get_vehicle($id) {
        return $this->db->get_where('vehicle', array('id' => $id))->row_array();
    }

    /*
     * Get all vehicle
     */

    function get_all_vehicle() {
        $this->db->order_by('id', 'desc');
        return $this->db->get('vehicle')->result_array();
    }

    /*
     * function to add new vehicle
     */

    function add_vehicle($params) {
        $this->db->insert('vehicle', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update vehicle
     */

    function update_vehicle($id, $params) {
        $this->db->where('id', $id);
        return $this->db->update('vehicle', $params);
    }

    /*
     * function to delete vehicle
     */

    function delete_vehicle($id) {
        return $this->db->delete('vehicle', array('id' => $id));
    }

    function get_vehicles_by_customer($customer_id) {
        if($customer_id)
            $query = $this->db->select("*")
                ->from('vehicle')->where("customerid", $customer_id);
        else
            return "[]";
        
        return $query->get()->result_array();
    }

}
